<?php

return [
    'clusters' => [
        'choice' => [
            'label' => 'Вибір дверей',
            'target_count' => 20,
            'summary' => 'Матеріали, які допомагають вибрати двері під приміщення, бюджет, клімат, безпеку і монтаж.',
            'titles' => [
                'yak-vybraty-vkhidni-dveri-dlia-kvartyry' => 'Як вибрати вхідні двері для квартири',
                'yak-vybraty-vkhidni-dveri-dlia-pryvatnoho-budynku' => 'Як вибрати вхідні двері для приватного будинку',
                'yak-vybraty-mizhkimnatni-dveri-dlia-kvartyry' => 'Як вибрати міжкімнатні двері для квартири',
                'dveri-dlia-ofisu-yak-obraty' => 'Двері для офісу: як обрати надійне рішення',
                'dveri-dlia-mahazynu-yak-obraty' => 'Двері для магазину: критерії вибору',
                'yak-vybraty-dveri-dlia-kotedzhu' => 'Як вибрати двері для котеджу',
                'vkhidni-chy-mizhkimnatni-dveri-riznytsia' => 'Вхідні та міжкімнатні двері: у чому різниця',
                'yak-obraty-dveri-za-biudzhetom' => 'Як обрати двері за бюджетом і не втратити якість',
                'yak-obraty-dveri-za-rozmirom' => 'Як обрати двері за розміром отвору',
                'yak-obraty-dveri-za-klimatom' => 'Як обрати двері з урахуванням клімату та опадів',
                'dveri-dlia-novobudovy-yak-obraty' => 'Двері для новобудови: що врахувати перед купівлею',
                'dveri-dlia-staroyi-kvartyry-yak-obraty' => 'Двері для старої квартири: як підібрати без помилок',
                'yak-obraty-dveri-dlia-orendnoho-zhytla' => 'Як обрати двері для орендного житла',
                'yak-obraty-dveri-dlia-komertsiinoho-prymishchennia' => 'Як обрати двері для комерційного приміщення',
                'yak-porivniuvaty-dveri-pered-pokupkoiu' => 'Як правильно порівнювати двері перед купівлею',
                'yak-chytaty-kharakterystyky-dverei' => 'Як читати характеристики дверей',
                'yak-obraty-dveri-z-montazhem' => 'Як обрати двері з монтажем',
                'yak-obraty-dveri-pid-zamovlennia' => 'Як обрати двері під замовлення',
                'deshevi-ta-yakisni-dveri-riznytsia' => 'Чим відрізняються дешеві та якісні двері',
                'checklist-vyboru-dverei' => 'Чеклист вибору дверей перед замовленням',
            ],
        ],
        'production' => [
            'label' => 'Технології виробництва',
            'target_count' => 20,
            'summary' => 'Пояснення конструкції дверей, матеріалів, утеплення, металу, терморозриву та виробничих вузлів.',
            'titles' => [
                'budova-vkhidnykh-dverei' => 'Будова вхідних дверей: полотно, коробка, ребра жорсткості',
                'budova-mizhkimnatnykh-dverei' => 'Будова міжкімнатних дверей і типи полотен',
                'termo-rozryv-shcho-tse' => 'Що таке терморозрив у дверях',
                'yak-pratsiuie-uteplyuvach-u-dveriakh' => 'Як працює утеплювач у дверях',
                'yaka-tovshchyna-metalu-u-dveriakh' => 'Яка товщина металу має бути у вхідних дверях',
                'rebra-zhorstkosti-u-dveriakh' => 'Ребра жорсткості у дверях: для чого вони потрібні',
                'kontury-ushchilnennia-u-dveriakh' => 'Контури ущільнення у дверях',
                'porih-u-vkhidnykh-dveriakh' => 'Поріг у вхідних дверях: види та помилки вибору',
                'petli-dlia-vkhidnykh-dverei' => 'Петлі для вхідних дверей: приховані, зовнішні, регульовані',
                'pokryttia-dverei-dlia-vulytsi' => 'Покриття дверей для вулиці: що витримує опади та сонце',
                'mdf-nakladky-na-dveriakh' => 'МДФ накладки на дверях: переваги та обмеження',
                'metalevyi-karkas-dverei' => 'Металевий каркас дверей: що впливає на міцність',
                'shumoizoliatsiia-u-dveriakh' => 'Шумоізоляція у дверях: які вузли дають результат',
                'enerhoefektyvnist-vkhidnykh-dverei' => 'Енергоефективність вхідних дверей',
                'tochka-rosy-i-kondensat-na-dveriakh' => 'Точка роси і конденсат на дверях',
                'mistok-kholodu-u-dveriakh' => 'Місток холоду у дверях: як його уникнути',
                'sklopakety-u-vkhidnykh-dveriakh' => 'Склопакети у вхідних дверях',
                'protypylezhni-dveri-konstruktsiia' => 'Протипожежні двері: конструкція та обмеження',
                'broniovani-dveri-konstruktsiia' => 'Броньовані двері: що означає посилена конструкція',
                'yakist-furnitury-dlia-dverei' => 'Якість фурнітури для дверей: що перевіряти',
            ],
        ],
        'installation' => [
            'label' => 'Монтаж',
            'target_count' => 20,
            'summary' => 'Практичні матеріали про замір, підготовку отвору, монтажні зазори, герметизацію, регулювання і типові помилки.',
            'titles' => [
                'montazh-vkhidnykh-dverei' => 'Як проходить монтаж вхідних дверей',
                'montazh-mizhkimnatnykh-dverei' => 'Як проходить монтаж міжкімнатних дверей',
                'yak-pravylno-zamiriaty-otvir-pid-dveri' => 'Як правильно заміряти отвір під двері',
                'pidhotovka-otvoru-pid-vkhidni-dveri' => 'Підготовка отвору під вхідні двері',
                'demontazh-starykh-dverei' => 'Демонтаж старих дверей: що може вплинути на монтаж',
                'montazhni-zazory-dlia-dverei' => 'Монтажні зазори для дверей',
                'yak-vystavyty-korobku-dverei' => 'Як виставляють коробку дверей',
                'ankeruvannia-dvernoi-korobky' => 'Анкерування дверної коробки',
                'hermetyzatsiia-montazhnoho-shva' => 'Герметизація монтажного шва',
                'montazh-dverei-u-hazobeton' => 'Монтаж дверей у газобетон',
                'montazh-dverei-u-tseglu' => 'Монтаж дверей у цегляну стіну',
                'montazh-dverei-u-panelnyi-budynok' => 'Монтаж дверей у панельному будинку',
                'montazh-dverei-pislia-remontu' => 'Монтаж дверей після ремонту',
                'montazh-dverei-do-remontu' => 'Монтаж дверей до ремонту',
                'dobory-i-lyshhtva-pislia-montazhu' => 'Добори і лиштва після монтажу',
                'rehuliuvannia-dverei-pislia-montazhu' => 'Регулювання дверей після монтажу',
                'pomylky-montazhu-vkhidnykh-dverei' => 'Типові помилки монтажу вхідних дверей',
                'chomu-dveri-zaiidaiut-pislia-montazhu' => 'Чому двері заїдають після монтажу',
                'montazh-dverei-z-termorozryvom' => 'Монтаж дверей з терморозривом',
                'yak-pryiniaty-robotu-pislia-montazhu' => 'Як прийняти роботу після монтажу дверей',
            ],
        ],
        'security' => [
            'label' => 'Безпека',
            'target_count' => 10,
            'summary' => 'Матеріали про замки, циліндри, зламостійкість, антивандальні рішення та практичну безпеку дверей.',
            'titles' => [
                'yaki-zamky-krashchi' => 'Які замки краще ставити у вхідні двері',
                'budova-dvernoho-zamka' => 'Будова дверного замка',
                'tsylindr-zamka-yak-obraty' => 'Циліндр замка: як обрати безпечний варіант',
                'suvaldnyi-chy-tsylindrovyi-zamok' => 'Сувальдний чи циліндровий замок: що краще',
                'zlamostiikist-vkhidnykh-dverei' => 'Зламостійкість вхідних дверей',
                'antyvandalni-dveri' => 'Антивандальні двері: де вони потрібні',
                'broniovani-dveri-dlia-kvartyry' => 'Броньовані двері для квартири',
                'dva-zamky-u-dveriakh' => 'Два замки у дверях: коли це виправдано',
                'zakhyst-vid-vysverdlennia-i-vybuvannia' => 'Захист замка від висвердлювання і вибивання',
                'bezpeka-dverei-dlia-komertsiinykh-obiektiv' => 'Безпека дверей для комерційних обʼєктів',
            ],
        ],
        'design' => [
            'label' => 'Дизайн',
            'target_count' => 10,
            'summary' => 'Поради щодо кольору, фактури, стилю, поєднання з фасадом, підлогою, меблями та освітленням.',
            'titles' => [
                'yak-obraty-kolir-vkhidnykh-dverei' => 'Як обрати колір вхідних дверей',
                'yak-obraty-kolir-mizhkimnatnykh-dverei' => 'Як обрати колір міжкімнатних дверей',
                'dveri-pid-dyzain-kvartyry' => 'Двері під дизайн квартири',
                'dveri-pid-fasad-budynku' => 'Двері під фасад приватного будинку',
                'matovi-chy-hliantsevi-dveri' => 'Матові чи глянцеві двері: що практичніше',
                'dveri-z-skliannymy-vstavkamy' => 'Двері зі скляними вставками',
                'minimalistychni-dveri' => 'Мінімалістичні двері: коли вони доречні',
                'klasychni-dveri-v-interieri' => 'Класичні двері в інтерʼєрі',
                'yak-poiednaty-dveri-z-pidlohoiu' => 'Як поєднати двері з підлогою',
                'yak-poiednaty-dveri-z-mebliamy' => 'Як поєднати двері з меблями',
            ],
        ],
        'care' => [
            'label' => 'Догляд',
            'target_count' => 10,
            'summary' => 'Інструкції з догляду, сервісу, ремонту, регулювання, очищення і профілактики проблем.',
            'titles' => [
                'yak-dohliadaty-za-vkhidnymy-dveryma' => 'Як доглядати за вхідними дверима',
                'yak-dohliadaty-za-mizhkimnatnymy-dveryma' => 'Як доглядати за міжкімнатними дверима',
                'chym-myty-dveri' => 'Чим мити двері без пошкодження покриття',
                'dohliad-za-zamkamy-i-furnituroiu' => 'Догляд за замками і фурнітурою',
                'yak-usunuty-skryp-dverei' => 'Як усунути скрип дверей',
                'yak-rehuliuvaty-dveri' => 'Як регулювати двері',
                'shcho-robyty-yakshcho-dveri-prosyly' => 'Що робити, якщо двері просіли',
                'kondensat-na-vkhidnykh-dveriakh' => 'Конденсат на вхідних дверях: причини і рішення',
                'remont-pokryttia-dverei' => 'Ремонт покриття дверей',
                'harantiia-i-servis-dverei' => 'Гарантія і сервіс дверей',
            ],
        ],
        'faq' => [
            'label' => 'Популярні питання',
            'target_count' => 10,
            'summary' => 'Стислі експертні відповіді на питання покупців, які часто виникають перед замовленням дверей.',
            'titles' => [
                'skilky-koshtuiut-yakisni-dveri' => 'Скільки коштують якісні двері',
                'chy-vkhodyt-montazh-u-vartist-dverei' => 'Чи входить монтаж у вартість дверей',
                'skilky-tryvaie-vyhotovlennia-dverei' => 'Скільки триває виготовлення дверей',
                'chy-mozhna-zrobyty-dveri-nestandartnoho-rozmiru' => 'Чи можна зробити двері нестандартного розміру',
                'koli-potriben-termorozryv' => 'Коли потрібен терморозрив',
                'yaka-harantiia-na-dveri' => 'Яка гарантія має бути на двері',
                'chy-mozhna-zaminyty-zamok-pislia-montazhu' => 'Чи можна замінити замок після монтажу',
                'shcho-robyty-yakshcho-dveri-ne-zakryvaiutsia' => 'Що робити, якщо двері не закриваються',
                'chy-potriben-profesiinyi-zamir' => 'Чи потрібен професійний замір',
                'yak-pidhotuvatysia-do-zamovlennia-dverei' => 'Як підготуватися до замовлення дверей',
            ],
        ],
    ],
];
