<?php

return [
    'page' => [
        'path' => '/nashi-roboty',
        'title' => 'Реальні встановлення дверей у Луцьку та Волині | Метр на Метр',
        'description' => 'Приклади встановлених вхідних та міжкімнатних дверей у Луцьку й Волинській області. Замір, підбір, доставка та монтаж від Метр на Метр.',
        'h1' => 'Реальні встановлення дверей у Луцьку та Волині',
        'intro' => 'Показуємо реальні фото дверей після монтажу у квартирах і приватних будинках. Без вигаданих адрес і постановочних кейсів.',
        'og_image' => '/images/real-works/real-installations-og.jpg',
    ],
    'filters' => [
        ['id' => 'all', 'label' => 'Усі роботи'],
        ['id' => 'entrance', 'label' => 'Вхідні двері'],
        ['id' => 'interior', 'label' => 'Міжкімнатні двері'],
        ['id' => 'installation', 'label' => 'Двері з монтажем'],
        ['id' => 'lutsk', 'label' => 'Луцьк'],
        ['id' => 'volyn', 'label' => 'Волинь'],
    ],
    'cases' => [
        [
            'id' => 'white-black-modern',
            'title' => 'Білі міжкімнатні двері з чорними вставками у сучасному інтер’єрі',
            'type' => 'Міжкімнатні двері',
            'location' => 'Луцьк',
            'description' => 'Світлі полотна з чорними вставками та фурнітурою підтримують стриманий сучасний інтер’єр. На фото — готовий результат після встановлення.',
            'services' => ['підбір', 'замір', 'доставка', 'монтаж'],
            'categories' => ['interior', 'installation', 'lutsk', 'volyn'],
            'cta' => 'Запитати ціну таких дверей',
            'images' => [
                [
                    'jpg' => '/images/real-works/white-black-interior-main.jpg',
                    'webp' => '/images/real-works/white-black-interior-main.webp',
                    'width' => 960,
                    'height' => 1280,
                    'alt' => 'Міжкімнатні двері з чорними вставками у сучасному інтер’єрі | Метр на Метр',
                ],
                [
                    'jpg' => '/images/real-works/white-black-interior-pair.jpg',
                    'webp' => '/images/real-works/white-black-interior-pair.webp',
                    'width' => 960,
                    'height' => 1280,
                    'alt' => 'Білі міжкімнатні двері після монтажу у Луцьку | Метр на Метр',
                ],
            ],
        ],
        [
            'id' => 'light-apartment',
            'title' => 'Світлі міжкімнатні двері для квартири у Луцьку',
            'type' => 'Міжкімнатні двері',
            'location' => 'для квартири',
            'description' => 'Світлі двері встановлено в готовому інтер’єрі квартири. Чорна фурнітура створює акуратний контраст зі стінами та підлогою.',
            'services' => ['підбір', 'замір', 'доставка', 'монтаж'],
            'categories' => ['interior', 'installation', 'lutsk', 'volyn'],
            'cta' => 'Підібрати такі двері',
            'images' => [
                [
                    'jpg' => '/images/real-works/light-apartment-main.jpg',
                    'webp' => '/images/real-works/light-apartment-main.webp',
                    'width' => 960,
                    'height' => 1280,
                    'alt' => 'Світлі міжкімнатні двері після монтажу у квартирі в Луцьку | Метр на Метр',
                ],
                [
                    'jpg' => '/images/real-works/light-apartment-angle.jpg',
                    'webp' => '/images/real-works/light-apartment-angle.webp',
                    'width' => 960,
                    'height' => 1280,
                    'alt' => 'Світлі двері з чорною фурнітурою в інтер’єрі квартири | Метр на Метр',
                ],
            ],
        ],
        [
            'id' => 'mirror-entrance-house',
            'title' => 'Вхідні двері з дзеркалом для приватного будинку',
            'type' => 'Вхідні двері',
            'location' => 'Волинська область',
            'description' => 'Вхідні двері з вертикальним дзеркалом встановлено у готовий отвір. Окремі кадри показують полотно та встановлену фурнітуру.',
            'services' => ['підбір', 'замір', 'доставка', 'монтаж'],
            'categories' => ['entrance', 'installation', 'volyn'],
            'cta' => 'Запитати ціну',
            'images' => [
                [
                    'jpg' => '/images/real-works/mirror-entrance-main.jpg',
                    'webp' => '/images/real-works/mirror-entrance-main.webp',
                    'width' => 960,
                    'height' => 1275,
                    'alt' => 'Вхідні двері з дзеркалом після встановлення у Волинській області | Метр на Метр',
                ],
                [
                    'jpg' => '/images/real-works/mirror-entrance-hardware.jpg',
                    'webp' => '/images/real-works/mirror-entrance-hardware.webp',
                    'width' => 960,
                    'height' => 1280,
                    'alt' => 'Фурнітура вхідних дверей після монтажу | Метр на Метр',
                ],
            ],
        ],
        [
            'id' => 'interior-fittings',
            'title' => 'Міжкімнатні двері з акуратним монтажем та фурнітурою',
            'type' => 'Міжкімнатні двері',
            'location' => 'Луцьк',
            'description' => 'Дверне полотно, лиштва та чорна фурнітура зібрані в одному стилі. Відкритий ракурс показує готовий монтаж у кімнаті.',
            'services' => ['замір', 'доставка', 'монтаж'],
            'categories' => ['interior', 'installation', 'lutsk', 'volyn'],
            'cta' => 'Замовити замір',
            'images' => [
                [
                    'jpg' => '/images/real-works/interior-fittings-main.jpg',
                    'webp' => '/images/real-works/interior-fittings-main.webp',
                    'width' => 960,
                    'height' => 1280,
                    'alt' => 'Міжкімнатні двері з чорною фурнітурою після монтажу у Луцьку | Метр на Метр',
                ],
                [
                    'jpg' => '/images/real-works/interior-fittings-open.jpg',
                    'webp' => '/images/real-works/interior-fittings-open.webp',
                    'width' => 960,
                    'height' => 1280,
                    'alt' => 'Відкриті міжкімнатні двері після встановлення | Метр на Метр',
                ],
            ],
        ],
        [
            'id' => 'installed-entrance-examples',
            'title' => 'Приклади встановлених вхідних дверей від Метр на Метр',
            'type' => 'Вхідні двері',
            'location' => 'Волинська область',
            'description' => 'Два окремі приклади вхідних дверей після встановлення: для квартири та для приватного будинку. Точні адреси клієнтів не публікуємо.',
            'services' => ['підбір', 'замір', 'доставка', 'монтаж'],
            'categories' => ['entrance', 'installation', 'volyn'],
            'cta' => 'Підібрати вхідні двері',
            'images' => [
                [
                    'jpg' => '/images/real-works/entrance-apartment-main.jpg',
                    'webp' => '/images/real-works/entrance-apartment-main.webp',
                    'width' => 960,
                    'height' => 1280,
                    'alt' => 'Вхідні двері після монтажу для квартири | Метр на Метр',
                ],
                [
                    'jpg' => '/images/real-works/entrance-house-main.jpg',
                    'webp' => '/images/real-works/entrance-house-main.webp',
                    'width' => 960,
                    'height' => 1280,
                    'alt' => 'Темні вхідні двері після встановлення у приватному будинку | Метр на Метр',
                ],
            ],
        ],
    ],
    'videos' => [
        [
            'id' => 'door-overview',
            'title' => 'Відеоогляд дверей та оздоблення',
            'src' => '/images/real-works/door-overview.mp4',
            'poster_jpg' => '/images/real-works/door-overview-poster.jpg',
            'poster_webp' => '/images/real-works/door-overview-poster.webp',
            'width' => 1072,
            'height' => 1904,
        ],
    ],
    'previews' => [
        'home' => ['white-black-modern', 'mirror-entrance-house', 'light-apartment', 'installed-entrance-examples'],
        'vkhidni-dveri-lutsk' => ['mirror-entrance-house', 'installed-entrance-examples'],
        'mizhkimnatni-dveri-lutsk' => ['white-black-modern', 'light-apartment', 'interior-fittings'],
        'dveri-volyn' => ['mirror-entrance-house', 'installed-entrance-examples', 'white-black-modern'],
        'dveri-z-montazhem-lutsk' => ['mirror-entrance-house', 'white-black-modern', 'installed-entrance-examples'],
        'metalovi-dveri-lutsk' => ['mirror-entrance-house', 'installed-entrance-examples'],
        'bronovani-dveri-lutsk' => ['installed-entrance-examples'],
        'vkhidni-dveri-v-budynok-lutsk' => ['mirror-entrance-house'],
        'vkhidni-dveri-v-kvartyru-lutsk' => ['installed-entrance-examples'],
        'mizhkimnatni-dveri-z-montazhem-lutsk' => ['white-black-modern', 'light-apartment', 'interior-fittings'],
    ],
];
